package com.example.repo.demo

import com.example.repo.model.AssetTypeData
import com.example.repo.model.TransactionDetailsResponseDataModel
import com.example.repo.model.TransactionItemResponseDataModel
import com.example.repo.model.TransactionTypeData

class TestData {
    companion object {
        fun getTestData(): ArrayList<TransactionItemResponseDataModel> {
            val transactions = ArrayList<TransactionItemResponseDataModel>()
            transactions.add(
                TransactionItemResponseDataModel(
                    1,
                    "assetName1",
                    0.023,
                    20.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    2,
                    "assetName2",
                    0.023,
                    21.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    3,
                    "assetName3",
                    0.023,
                    22.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    4,
                    "assetName4",
                    0.023,
                    25.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    5,
                    "assetName5",
                    0.023,
                    29.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    6,
                    "assetName6",
                    0.005,
                    26.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    7,
                    "assetName7",
                    0.023,
                    20.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.STOCK,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    8,
                    "assetName8",
                    0.023,
                    20.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    9,
                    "assetName9",
                    0.023,
                    30.5,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CURRENCY,
                    TransactionTypeData.SELL
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    1,
                    "assetName1",
                    0.023,
                    20.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    2,
                    "assetName2",
                    0.023,
                    21.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    3,
                    "assetName3",
                    0.023,
                    22.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    4,
                    "assetName4",
                    0.023,
                    25.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    5,
                    "assetName5",
                    0.023,
                    29.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    6,
                    "assetName6",
                    0.005,
                    26.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    7,
                    "assetName7",
                    0.023,
                    20.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.STOCK,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    8,
                    "assetName8",
                    0.023,
                    20.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    9,
                    "assetName9",
                    0.023,
                    30.5,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CURRENCY,
                    TransactionTypeData.SELL
                )
            )
            return transactions
        }

        fun getTestDataForSearchQuery(): ArrayList<TransactionItemResponseDataModel> {
            val transactions = ArrayList<TransactionItemResponseDataModel>()
            transactions.add(
                TransactionItemResponseDataModel(
                    1,
                    "assetName1",
                    0.023,
                    20.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    2,
                    "assetName2",
                    0.023,
                    21.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    3,
                    "assetName3",
                    0.023,
                    22.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    4,
                    "assetName4",
                    0.023,
                    25.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    5,
                    "assetName5",
                    0.023,
                    29.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    6,
                    "assetName6",
                    0.005,
                    26.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    7,
                    "assetName7",
                    0.023,
                    20.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.STOCK,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    8,
                    "assetName8",
                    0.023,
                    20.0,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CRYPTO,
                    TransactionTypeData.BUY
                )
            )
            transactions.add(
                TransactionItemResponseDataModel(
                    9,
                    "assetName9",
                    0.023,
                    30.5,
                    "EUR",
                    1638120473231,
                    AssetTypeData.CURRENCY,
                    TransactionTypeData.SELL
                )
            )
            return transactions
        }

        fun getTransactionDetailsTestData(transactionId: Int): TransactionDetailsResponseDataModel {
            val data = getTestData()
            if (!data.isNullOrEmpty()) {
                for (transactionItem in data) {
                    if (transactionId.equals(transactionItem.transactionId)) {
                        return TransactionDetailsResponseDataModel(
                            transactionItem.transactionId,
                            transactionItem.assetsName,
                            transactionItem.quantity,
                            transactionItem.price,
                            transactionItem.priceCurrency,
                            transactionItem.date,
                            transactionItem.assetType,
                            transactionItem.transactionType
                        )
                    }
                }
            }
            return TransactionDetailsResponseDataModel(
                0,
                "",
                0.0,
                0.0,
                "",
                0,
                AssetTypeData.CRYPTO,
                TransactionTypeData.BUY
            )
        }
    }
}